/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xy_jjl_utils_CashBoxCheck */

#ifndef _Included_com_xy_jjl_utils_CashBoxCheck
#define _Included_com_xy_jjl_utils_CashBoxCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xy_jjl_utils_CashBoxCheck
 * Method:    jCashBoxDeviceInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xy_jjl_utils_CashBoxCheck_jCashBoxDeviceInit
  (JNIEnv *, jobject);

/*
 * Class:     com_xy_jjl_utils_CashBoxCheck
 * Method:    jCashBoxStatusGet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xy_jjl_utils_CashBoxCheck_jCashBoxStatusGet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
