/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xy_jjl_utils_PrinterUnit */

#ifndef _Included_com_xy_jjl_utils_PrinterUnit
#define _Included_com_xy_jjl_utils_PrinterUnit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xy_jjl_utils_PrinterUnit
 * Method:    jPrinterInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xy_jjl_utils_PrinterUnit_jPrinterInit
  (JNIEnv *, jobject);

/*
 * Class:     com_xy_jjl_utils_PrinterUnit
 * Method:    jPrinterDataSend
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_xy_jjl_utils_PrinterUnit_jPrinterDataSend
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
